/**
 * Phase 10 Session 5 — writes/resets `buildDocsFixturePlan()`'s output to a
 * real, isolated directory on disk. Deliberately independent of Tauri: this
 * never runs inside the packed app, never touches `app.path().app_data_dir()`
 * (`%APPDATA%\com.formulab.app` on Windows), and never reads the real dev
 * checkout's own `data/`/`formulas/`/`.FormuLab/` (which IS this developer's
 * real, live project — see the module doc comment in `build.ts`). It writes
 * plain files at the exact relative paths `masterdata.rs`/`formulation_v2.rs`
 * already read, so pointing the real app's `formulab-root.txt` override at
 * this folder (a manual, human, opt-in step — never done by this module)
 * would make the app treat it as a real project.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { buildDocsFixturePlan, type DocsFixturePlan } from "./build";

export class UnsafeFixtureRootError extends Error {}

/** Written into the fixture root once seeded. Its presence is the ONLY
 *  thing that makes a directory "known safe to wipe and reseed" — a
 *  directory without it is always treated as someone else's, regardless of
 *  what its path looks like. */
export const DOCS_FIXTURE_MARKER_FILENAME = ".formulab-docs-fixture-profile";
const DOCS_FIXTURE_MARKER_CONTENT =
  "This directory is a FormuLab documentation fixture profile, generated by\n" +
  "apps/desktop/src/lib/docsFixture — safe to delete or regenerate at will.\n" +
  "It is never the real app-data profile and contains no real project data.\n";

/** Path fragments that mean "this looks like a REAL profile location" —
 *  matched case-insensitively against the normalized (forward-slash)
 *  absolute path. Any match refuses the call outright, regardless of the
 *  directory's actual contents. Deliberately NOT a bare "appdata": the OS
 *  temp directory tests run against (and any legitimate scratch location)
 *  commonly lives under `...\AppData\Local\Temp\...` too — the real Tauri
 *  profile is identified by its actual bundle-id folder instead. */
const FORBIDDEN_PATH_FRAGMENTS = ["appdata/roaming/com.formulab.app", "com.formulab.app", "documents/formulab"];

/** The leaf folder name every real fixture root must contain, so a typo'd
 *  or programmatically-derived path can never silently target an arbitrary
 *  directory. */
const REQUIRED_ROOT_NAME_FRAGMENT = "docs-fixture";

function normalize(p: string): string {
  return p.replace(/\\/g, "/").toLowerCase();
}

/** Fail closed on anything that isn't unambiguously a dedicated, disposable
 *  fixture directory — never assume a path is safe because it "probably
 *  isn't" the real profile. */
export function assertSafeFixtureRoot(root: string): void {
  if (!path.isAbsolute(root)) {
    throw new UnsafeFixtureRootError(`docs fixture root must be an absolute path, got: ${root}`);
  }
  const normalized = normalize(root);
  for (const fragment of FORBIDDEN_PATH_FRAGMENTS) {
    if (normalized.includes(fragment)) {
      throw new UnsafeFixtureRootError(
        `refusing to use "${root}" as the docs fixture root — it looks like a real profile location (matched "${fragment}").`,
      );
    }
  }
  if (!normalize(path.basename(root)).includes(REQUIRED_ROOT_NAME_FRAGMENT)) {
    throw new UnsafeFixtureRootError(
      `docs fixture root's own folder name must contain "${REQUIRED_ROOT_NAME_FRAGMENT}", got: ${path.basename(root)}`,
    );
  }
}

/** Fail closed if a directory already exists, is non-empty, and was not
 *  itself created by this module (no marker file) — never assume an
 *  arbitrary populated folder is safe to write into. */
function assertKnownFixtureOrEmpty(root: string): void {
  if (!fs.existsSync(root)) return;
  const entries = fs.readdirSync(root);
  if (entries.length === 0) return;
  if (!entries.includes(DOCS_FIXTURE_MARKER_FILENAME)) {
    throw new UnsafeFixtureRootError(
      `"${root}" already exists, is not empty, and has no docs-fixture marker file — refusing to touch it.`,
    );
  }
}

function writePlan(root: string, plan: DocsFixturePlan): void {
  for (const [relPath, content] of Object.entries(plan.files)) {
    const abs = path.join(root, ...relPath.split("/"));
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    const text = typeof content === "string" ? content : `${JSON.stringify(content, null, 2)}\n`;
    fs.writeFileSync(abs, text, "utf8");
  }
}

/** Seed a brand-new (or previously-seeded) documentation fixture at `root`.
 *  Refuses a real-profile-looking path, and refuses an existing directory
 *  that isn't already a known fixture. Idempotent: calling this again on an
 *  already-seeded root reproduces byte-identical files (the plan is
 *  deterministic — see `build.test.ts`). */
export function seedDocsFixture(root: string): DocsFixturePlan {
  assertSafeFixtureRoot(root);
  assertKnownFixtureOrEmpty(root);
  const plan = buildDocsFixturePlan();
  fs.mkdirSync(root, { recursive: true });
  writePlan(root, plan);
  fs.writeFileSync(path.join(root, DOCS_FIXTURE_MARKER_FILENAME), DOCS_FIXTURE_MARKER_CONTENT, "utf8");
  return plan;
}

/** Wipe and reseed an EXISTING documentation fixture. Unlike `seedDocsFixture`,
 *  this requires the marker file to already be present — "reset" means
 *  "start this fixture over," never "adopt an arbitrary folder." */
export function resetDocsFixture(root: string): DocsFixturePlan {
  assertSafeFixtureRoot(root);
  if (!fs.existsSync(root) || !fs.readdirSync(root).includes(DOCS_FIXTURE_MARKER_FILENAME)) {
    throw new UnsafeFixtureRootError(`"${root}" is not an existing docs-fixture profile — seed it first.`);
  }
  fs.rmSync(root, { recursive: true, force: true });
  return seedDocsFixture(root);
}

/** The default fixture root: a dedicated, gitignored folder at the repo
 *  root, sibling to (never inside) the real `data`/`formulas`/`.FormuLab`
 *  directories. */
export function defaultDocsFixtureRoot(repoRoot: string): string {
  return path.join(repoRoot, ".docs-fixture");
}
