import { RawMaterial } from '../schemas/materials';
import { IngredientMappingResult } from './ingredientMapper';
import { AnalyticalAnalysis } from './analyticalInference';
import {
  ReverseConstraintSet,
  TargetProductProfile,
  IngredientDeclarationLine,
} from '../schemas/reverseFormulation';
import { computeTargetMatchScore } from './scoringModel';

/**
 * Input for candidate generation.
 */
export interface GenerationInput {
  /** Mapped ingredients from declaration lines. */
  mappedIngredients: Array<{
    line: IngredientDeclarationLine;
    mapping: IngredientMappingResult;
  }>;
  /** Analytical insights. */
  analysis: AnalyticalAnalysis;
  /** Target product profile. */
  target: TargetProductProfile;
  /** Constraints derived from evidence, targets, regulations. */
  constraints: ReverseConstraintSet;
  /** Available materials in catalog (filtered by constraints). */
  availableMaterials: RawMaterial[];
}

/**
 * A generated formula candidate.
 */
export interface GeneratedCandidate {
  /** List of materials with percentages. */
  formula: Array<{
    materialId: string;
    percentage: number;
    function?: string;
  }>;
  /** Estimated properties. */
  estimatedProperties: Record<string, number>;
  /** How well it matches the target. */
  matchScore: number;
  /** Reasoning. */
  notes: string[];
}

/** Result of one generation method: a candidate, or an honest reason it
 *  produced nothing. */
interface GenerationAttempt {
  candidate: GeneratedCandidate | null;
  /** Present when `candidate` is null: why this method produced nothing. */
  rejectionReason?: string;
}

/**
 * Generate formula candidates based on inputs.
 * This is a simplified generator that creates a few basic formulas.
 * Deterministic: identical input always produces identical, identically
 * ordered output — no randomness, no wall-clock dependence.
 */
export function generateCandidates(input: GenerationInput): GeneratedCandidate[] {
  const { mappedIngredients, analysis, target, constraints, availableMaterials } = input;

  // If no mapped ingredients, we cannot generate meaningful candidates.
  if (mappedIngredients.length === 0) {
    return [
      {
        formula: [],
        estimatedProperties: {},
        matchScore: 0,
        notes: ['No mapped ingredients to base formulation on.'],
      },
    ];
  }

  const attempts: GenerationAttempt[] = [
    generateFromDeclaredHints(mappedIngredients, availableMaterials, target, constraints),
    generateBaselineFormula(mappedIngredients, availableMaterials, target, constraints),
    generateFromAnalytical(mappedIngredients, availableMaterials, analysis, target, constraints),
  ];

  const rejectionReasons: string[] = [];
  const candidates: GeneratedCandidate[] = [];
  const seenFormulas = new Set<string>();

  for (const attempt of attempts) {
    if (!attempt.candidate) {
      if (attempt.rejectionReason) rejectionReasons.push(attempt.rejectionReason);
      continue;
    }
    const signature = formulaSignature(attempt.candidate.formula);
    if (seenFormulas.has(signature)) {
      rejectionReasons.push(
        'A candidate with an identical formula was already generated by another method; not listed separately.'
      );
      continue;
    }
    seenFormulas.add(signature);
    candidates.push(attempt.candidate);
  }

  // If we have no candidates, return an explicit, explained fallback rather
  // than a misleading empty-but-unexplained result.
  if (candidates.length === 0) {
    candidates.push({
      formula: [],
      estimatedProperties: {},
      matchScore: 0,
      notes: ['Could not generate any candidate formulas.', ...rejectionReasons],
    });
  }

  return candidates;
}

/** Canonical, order-independent identity of a formula: same materials at
 *  the same rounded percentages are the same candidate, regardless of
 *  which generation method produced them or what it labeled the function as. */
function formulaSignature(formula: GeneratedCandidate['formula']): string {
  return formula
    .map(l => `${l.materialId}:${l.percentage.toFixed(2)}`)
    .sort()
    .join('|');
}

/** An invalid/non-finite number is not a valid percentage — treat as 0
 *  rather than propagating NaN/Infinity into a formula. */
function roundTo2(n: number): number {
  if (!Number.isFinite(n)) return 0;
  return Math.round(n * 100) / 100;
}

/** Round each line to 2dp and push any rounding residual onto the largest
 *  line, so the formula's total matches `targetTotal` exactly instead of
 *  drifting by a cent from independent per-line rounding. Never produces a
 *  negative percentage. */
function normalizeToTotal(
  formula: GeneratedCandidate['formula'],
  targetTotal: number
): GeneratedCandidate['formula'] {
  if (formula.length === 0) return formula;
  const rounded = formula.map(l => ({ ...l, percentage: Math.max(0, roundTo2(l.percentage)) }));
  const sum = rounded.reduce((s, l) => s + l.percentage, 0);
  const residual = roundTo2(targetTotal - sum);
  if (residual !== 0) {
    let largestIndex = 0;
    for (let i = 1; i < rounded.length; i++) {
      if (rounded[i].percentage > rounded[largestIndex].percentage) largestIndex = i;
    }
    rounded[largestIndex] = {
      ...rounded[largestIndex],
      percentage: Math.max(0, roundTo2(rounded[largestIndex].percentage + residual)),
    };
  }
  return rounded;
}

/** Checks a finished formula against the study's constraints. Returns a
 *  human-readable violation, or null if the formula is acceptable. We
 *  reject rather than silently reflow percentages to satisfy constraints —
 *  that would require real optimization, out of scope here. */
function validateAgainstConstraints(
  formula: GeneratedCandidate['formula'],
  constraints: ReverseConstraintSet
): string | null {
  for (const line of formula) {
    const min = constraints.minimumPercentages[line.materialId];
    if (min !== undefined && line.percentage < min) {
      return `${line.materialId} at ${line.percentage.toFixed(2)}% is below the required minimum of ${min}%.`;
    }
    const max = constraints.maximumPercentages[line.materialId];
    if (max !== undefined && line.percentage > max) {
      return `${line.materialId} at ${line.percentage.toFixed(2)}% exceeds the maximum of ${max}%.`;
    }
  }
  for (const required of constraints.requiredMaterials) {
    if (!formula.some(l => l.materialId === required)) {
      return `Required material ${required} is missing from the formula.`;
    }
  }
  return null;
}

/**
 * Generate a candidate by respecting declared order and concentration hints.
 */
function generateFromDeclaredHints(
  mappedIngredients: Array<{
    line: IngredientDeclarationLine;
    mapping: IngredientMappingResult;
  }>,
  availableMaterials: RawMaterial[],
  target: TargetProductProfile,
  constraints: ReverseConstraintSet
): GenerationAttempt {
  // We'll attempt to assign percentages based on concentration hints or assume descending order.
  const materialsWithCandidates: Array<{
    material: RawMaterial;
    declaredName: string;
    order: number;
    concentrationHint: string | undefined;
    functionHint: string | undefined;
  }> = [];

  for (const item of mappedIngredients) {
    const mat = item.mapping.material;
    if (!mat) continue;
    if (constraints.excludedMaterials.includes(mat.code)) continue;
    materialsWithCandidates.push({
      material: mat,
      declaredName: item.line.declaredName,
      order: item.line.declaredOrder,
      concentrationHint: item.line.concentrationHint,
      functionHint: item.line.functionHint,
    });
  }

  if (materialsWithCandidates.length === 0) {
    return {
      candidate: null,
      rejectionReason:
        'Declared-order candidate: every mapped ingredient was unmapped or excluded by constraints.',
    };
  }

  // Sort by declared order (stable: ties keep declaration order).
  materialsWithCandidates.sort((a, b) => a.order - b.order);

  // Assign percentages: if we have concentration hints, try to use them; otherwise distribute evenly.
  const total = 100;
  let remaining = total;
  const formula: GeneratedCandidate['formula'] = [];

  for (const item of materialsWithCandidates) {
    let percent = 0;
    if (item.concentrationHint) {
      // Extract number from hint (e.g., "5%" -> 5)
      const match = item.concentrationHint.match(/(\d+(?:\.\d+)?)%?/);
      if (match) {
        const val = parseFloat(match[1]);
        // If it's a range like "2-4%", take the midpoint.
        if (item.concentrationHint.includes('-')) {
          const parts = item.concentrationHint.split('-').map(p => parseFloat(p.trim()));
          if (parts.length === 2 && parts.every(Number.isFinite)) {
            const min = Math.min(parts[0], parts[1]);
            const max = Math.max(parts[0], parts[1]);
            percent = (min + max) / 2;
          } else {
            percent = val;
          }
        } else {
          percent = val;
        }
        if (!Number.isFinite(percent)) percent = 0;
        // Clamp to remaining
        if (percent > remaining) percent = remaining;
      }
    }
    if (percent === 0 && remaining > 0) {
      // Blank/unparseable hints are not treated as "0%" — distribute the
      // remaining budget evenly among the items still to be placed.
      const remainingCount = materialsWithCandidates.length - materialsWithCandidates.indexOf(item);
      percent = remaining / remainingCount;
    }
    // Ensure we don't go negative or non-finite
    if (!Number.isFinite(percent) || percent < 0) percent = 0;
    if (percent > remaining) percent = remaining;

    // Respect a per-material constraint ceiling, if one is declared.
    const maxAllowed = constraints.maximumPercentages[item.material.code];
    if (maxAllowed !== undefined && percent > maxAllowed) percent = maxAllowed;

    formula.push({
      materialId: item.material.code,
      percentage: roundTo2(percent),
      function: item.functionHint || undefined,
    });

    remaining -= percent;
    if (remaining <= 0) break;
  }

  // If there's leftover, add to the first ingredient (usually water)
  if (remaining > 0 && formula.length > 0) {
    formula[0] = { ...formula[0], percentage: roundTo2(formula[0].percentage + remaining) };
  }

  const normalized = normalizeToTotal(formula, total);

  const violation = validateAgainstConstraints(normalized, constraints);
  if (violation) {
    return { candidate: null, rejectionReason: `Declared-order candidate rejected: ${violation}` };
  }

  const estimatedProps = estimateProperties(normalized, availableMaterials);
  const matchScore = computeTargetMatchScore(estimatedProps, target);

  return {
    candidate: {
      formula: normalized,
      estimatedProperties: estimatedProps,
      matchScore,
      notes: [
        'Generated based on declared order and concentration hints.',
        `Used ${normalized.length} ingredients.`,
      ],
    },
  };
}

/**
 * Generate a baseline formula: water, surfactant, thickener, preservative.
 */
function generateBaselineFormula(
  mappedIngredients: Array<{
    line: IngredientDeclarationLine;
    mapping: IngredientMappingResult;
  }>,
  availableMaterials: RawMaterial[],
  target: TargetProductProfile,
  constraints: ReverseConstraintSet
): GenerationAttempt {
  const usableMaterials = availableMaterials.filter(m => !constraints.excludedMaterials.includes(m.code));

  // We'll try to find materials that match common functions.
  const water = usableMaterials.find(m =>
    m.functions?.includes('solvent') &&
    (m.inciName?.toLowerCase().includes('aqua') || m.displayName.toLowerCase().includes('water'))
  );
  const surfactant = usableMaterials.find(m =>
    m.functions?.some(f =>
      ['anionic_surfactant', 'nonionic_surfactant', 'cationic_surfactant', 'amphoteric_surfactant'].includes(f)
    )
  );
  const thickener = usableMaterials.find(m =>
    m.functions?.includes('rheology_modifier')
  );
  const preservative = usableMaterials.find(m =>
    m.functions?.includes('preservative')
  );

  const selected: Array<{ material: RawMaterial; percentage: number; function: string }> = [];

  if (water) selected.push({ material: water, percentage: 60, function: 'solvent' });
  if (surfactant) selected.push({ material: surfactant, percentage: 15, function: surfactant.functions?.[0] || 'surfactant' });
  if (thickener) selected.push({ material: thickener, percentage: 3, function: 'rheology_modifier' });
  if (preservative) selected.push({ material: preservative, percentage: 0.5, function: 'preservative' });

  if (selected.length === 0) {
    return {
      candidate: null,
      rejectionReason:
        'Baseline candidate: no solvent, surfactant, rheology modifier, or preservative found in the available (non-excluded) material catalog.',
    };
  }

  // Adjust to sum to 100% by scaling water, when a water line exists.
  let total = selected.reduce((sum, item) => sum + item.percentage, 0);
  if (total > 0 && total < 100) {
    const waterItem = selected.find(i => i.function === 'solvent');
    if (waterItem) {
      waterItem.percentage += 100 - total;
      total = 100;
    }
  }

  const rawFormula: GeneratedCandidate['formula'] = selected.map(item => ({
    materialId: item.material.code,
    percentage: roundTo2(item.percentage),
    function: item.function,
  }));

  const formula = normalizeToTotal(rawFormula, roundTo2(total));

  const violation = validateAgainstConstraints(formula, constraints);
  if (violation) {
    return { candidate: null, rejectionReason: `Baseline candidate rejected: ${violation}` };
  }

  const estimatedProps = estimateProperties(formula, availableMaterials);
  const matchScore = computeTargetMatchScore(estimatedProps, target);

  return {
    candidate: {
      formula,
      estimatedProperties: estimatedProps,
      matchScore,
      notes: [
        'Generated baseline formula (water, surfactant, thickener, preservative).',
        total >= 100
          ? 'Adjusted to sum to 100%.'
          : `Total is ${total.toFixed(2)}% — could not reach 100% with the available baseline materials.`,
      ],
    },
  };
}

/**
 * Generate a candidate by matching analytes to materials.
 */
function generateFromAnalytical(
  mappedIngredients: Array<{
    line: IngredientDeclarationLine;
    mapping: IngredientMappingResult;
  }>,
  availableMaterials: RawMaterial[],
  analysis: AnalyticalAnalysis,
  target: TargetProductProfile,
  constraints: ReverseConstraintSet
): GenerationAttempt {
  if (analysis.totalAnalytes === 0) {
    return {
      candidate: null,
      rejectionReason:
        'Analytical candidate: no analytical composition data was provided, so no analytical-based candidate was attempted.',
    };
  }
  // No analyte-to-material quantification model exists yet (out of scope for
  // this session) — reuse the declared-hints method rather than fabricate a
  // distinct analytical formula. `generateCandidates` drops this candidate
  // as a duplicate if it ends up identical to another one.
  const base = generateFromDeclaredHints(mappedIngredients, availableMaterials, target, constraints);
  if (!base.candidate) {
    return {
      candidate: null,
      rejectionReason: base.rejectionReason
        ? `Analytical candidate: ${base.rejectionReason}`
        : 'Analytical candidate: underlying declared-order generation failed.',
    };
  }
  return {
    candidate: {
      ...base.candidate,
      notes: [
        ...base.candidate.notes,
        'Analytical data is present but no analyte-to-material quantification model exists yet; this matches the declared-order candidate.',
      ],
    },
  };
}

/**
 * Estimate properties of a formula based on its components.
 * Very simplified: just average of some properties weighted by fraction.
 */
function estimateProperties(
  formula: Array<{ materialId: string; percentage: number; function?: string }>,
  materials: ReadonlyArray<RawMaterial>
): Record<string, number> {
  const map = new Map<string, RawMaterial>();
  for (const mat of materials) {
    map.set(mat.code, mat);
  }

  let totalWeight = 0;
  const props: Record<string, number> = {};

  for (const comp of formula) {
    const mat = map.get(comp.materialId);
    if (!mat) continue;
    const weight = comp.percentage / 100; // fraction
    totalWeight += weight;

    // Example properties: active matter, pH (if available), viscosity (if available)
    // We'll just sum whatever numeric properties we have, but this is naive.
    // In reality, you'd need mixing rules.
    if (mat.activeMatterPercent !== undefined) {
      const amt = parseFloat(mat.activeMatterPercent);
      if (Number.isFinite(amt)) {
        props.activeMatter = (props.activeMatter ?? 0) + amt * weight;
      }
    }
    // For pH, we cannot simply average; we'll skip.
  }

  // Normalize by total weight (should be 1 if percentages sum to 100)
  if (totalWeight > 0) {
    for (const key of Object.keys(props)) {
      props[key] = props[key] / totalWeight;
    }
  }

  return props;
}
