import { matchPath } from "react-router-dom";
import { HELP_SCHEMA_VERSION, type HelpTopic } from "./types";

/**
 * The one central help registry. Maps onto `router.tsx`'s existing paths
 * and reuses `Sidebar.tsx`'s own nav-item keys as topic/module ids — this
 * is not a second route registry or a second navigation definition, only
 * a lookup from an existing route to its help content's metadata. Content
 * (title/summary/etc.) lives in `i18n/locales/<locale>/help.json` under
 * each topic's `id`; nothing here is user-facing prose.
 *
 * Every entry's `contentStatus`/`knownLimitationKeys` are grounded in
 * `docs/PHASE10_COVERAGE_MATRIX.md` — never asserted independently of it.
 */
export const HELP_TOPICS: HelpTopic[] = [
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "home",
    module: "home",
    routes: [{ path: "/home" }],
    titleKey: "home.title",
    summaryKey: "home.summary",
    purposeKey: "home.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["home.quickStart.0", "home.quickStart.1"],
    sectionKeys: ["home.sections.0", "home.sections.1", "home.sections.2", "home.sections.3", "home.sections.4"],
    warningKeys: [],
    roleNoteKeys: [],
    knownLimitationKeys: ["home.limitations.0"],
    relatedTopicIds: ["projects", "approval"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["dashboard", "recent projects", "activity", "overview"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "projects",
    module: "projects",
    routes: [{ path: "/projects" }],
    titleKey: "projects.title",
    summaryKey: "projects.summary",
    purposeKey: "projects.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["projects.quickStart.0", "projects.quickStart.1", "projects.quickStart.2"],
    sectionKeys: ["projects.sections.0"],
    warningKeys: [],
    roleNoteKeys: [],
    knownLimitationKeys: [],
    relatedTopicIds: ["home", "formulation", "dataExchange"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["project", "new project", "product family", "packaging sku"],
    contentStatus: "current",
  },
  {
    // The "formulation" tour (lib/help/tours.ts) targets real elements on
    // /live (FormulationStudio's target/category/market/Generate, and
    // CardsView's V1/V2/V3/Card/Edit/function-totals/warnings), not this
    // topic's own /formulation route — /formulation is the saved-version
    // editing workspace, while /live is where a formulation is actually
    // generated. `Tour.route` handles the navigation; this topic just
    // offers the "Start tour" entry point under its thematic name.
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "formulation",
    module: "formulation",
    routes: [{ path: "/formulation" }],
    titleKey: "formulation.title",
    summaryKey: "formulation.summary",
    purposeKey: "formulation.purpose",
    prerequisiteKeys: ["formulation.prerequisites.0"],
    quickStartStepKeys: ["formulation.quickStart.0", "formulation.quickStart.1", "formulation.quickStart.2"],
    sectionKeys: [
      "formulation.sections.0", "formulation.sections.1", "formulation.sections.2",
      "formulation.sections.3", "formulation.sections.4", "formulation.sections.5",
    ],
    warningKeys: ["formulation.warnings.0"],
    roleNoteKeys: ["formulation.roleNotes.0"],
    knownLimitationKeys: [],
    relatedTopicIds: ["laboratory", "stability", "regulatory", "approval", "optimization"],
    glossaryTermIds: ["workingDraft", "savedVersion", "qsToHundred", "blockingFinding"],
    screenshotIds: [],
    tourId: "formulation",
    keywords: ["formula", "grid", "builder", "versions", "cost", "compatibility", "safety", "packaging"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "optimization",
    module: "formulation",
    routes: [{ path: "/optimization" }],
    titleKey: "optimization.title",
    summaryKey: "optimization.summary",
    purposeKey: "optimization.purpose",
    prerequisiteKeys: ["optimization.prerequisites.0"],
    quickStartStepKeys: ["optimization.quickStart.0", "optimization.quickStart.1"],
    sectionKeys: ["optimization.sections.0", "optimization.sections.1"],
    warningKeys: [],
    roleNoteKeys: [],
    knownLimitationKeys: ["optimization.limitations.0"],
    relatedTopicIds: ["formulation", "optimizer"],
    glossaryTermIds: ["workingDraft"],
    screenshotIds: [],
    keywords: ["optimizer", "constraint", "objective", "scenario"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "optimizer",
    module: "optimizer",
    routes: [{ path: "/optimizer" }],
    linkOnly: true,
    titleKey: "optimizer.title",
    summaryKey: "optimizer.summary",
    purposeKey: "optimizer.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["optimizer.quickStart.0"],
    sectionKeys: [],
    warningKeys: [],
    roleNoteKeys: [],
    knownLimitationKeys: [],
    relatedTopicIds: ["optimization"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["what-if", "calculator", "standalone optimizer"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "doe",
    module: "formulation",
    routes: [{ path: "/doe" }],
    titleKey: "doe.title",
    summaryKey: "doe.summary",
    purposeKey: "doe.purpose",
    prerequisiteKeys: ["doe.prerequisites.0"],
    quickStartStepKeys: ["doe.quickStart.0", "doe.quickStart.1", "doe.quickStart.2"],
    sectionKeys: [
      "doe.sections.0", "doe.sections.1", "doe.sections.2", "doe.sections.3",
      "doe.sections.4", "doe.sections.5", "doe.sections.6", "doe.sections.7",
    ],
    warningKeys: [],
    roleNoteKeys: [],
    knownLimitationKeys: ["doe.limitations.0", "doe.limitations.1"],
    relatedTopicIds: ["formulation", "laboratory", "optimization"],
    glossaryTermIds: ["doeStudy", "savedVersion"],
    screenshotIds: [],
    tourId: "doe",
    keywords: ["design of experiments", "factors", "responses", "analysis", "candidates"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "reverseFormulation",
    module: "formulation",
    routes: [{ path: "/reverse-formulation" }],
    titleKey: "reverseFormulation.title",
    summaryKey: "reverseFormulation.summary",
    purposeKey: "reverseFormulation.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["reverseFormulation.quickStart.0", "reverseFormulation.quickStart.1", "reverseFormulation.quickStart.2"],
    sectionKeys: ["reverseFormulation.sections.0", "reverseFormulation.sections.1", "reverseFormulation.sections.2"],
    warningKeys: ["reverseFormulation.warnings.0"],
    roleNoteKeys: [],
    knownLimitationKeys: ["reverseFormulation.limitations.0"],
    relatedTopicIds: ["formulation"],
    glossaryTermIds: ["reverseFormulationCandidate"],
    screenshotIds: [],
    keywords: ["benchmark", "declared ingredients", "candidate", "evidence confidence"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "laboratory",
    module: "laboratory",
    routes: [{ path: "/laboratory" }],
    titleKey: "laboratory.title",
    summaryKey: "laboratory.summary",
    purposeKey: "laboratory.purpose",
    prerequisiteKeys: ["laboratory.prerequisites.0"],
    quickStartStepKeys: ["laboratory.quickStart.0", "laboratory.quickStart.1", "laboratory.quickStart.2"],
    sectionKeys: ["laboratory.sections.0", "laboratory.sections.1", "laboratory.sections.2", "laboratory.sections.3"],
    warningKeys: ["laboratory.warnings.0"],
    roleNoteKeys: ["laboratory.roleNotes.0"],
    knownLimitationKeys: ["laboratory.limitations.0"],
    relatedTopicIds: ["stability", "formulation"],
    glossaryTermIds: ["savedVersion", "testMethodSnapshot"],
    screenshotIds: [],
    keywords: ["trial", "test definitions", "corrective action", "deviation", "weighing"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "stability",
    module: "laboratory",
    routes: [{ path: "/stability" }],
    titleKey: "stability.title",
    summaryKey: "stability.summary",
    purposeKey: "stability.purpose",
    prerequisiteKeys: ["stability.prerequisites.0"],
    quickStartStepKeys: ["stability.quickStart.0", "stability.quickStart.1"],
    sectionKeys: [],
    warningKeys: ["stability.warnings.0"],
    roleNoteKeys: [],
    knownLimitationKeys: ["stability.limitations.0"],
    relatedTopicIds: ["laboratory"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["stability study", "sample", "trend", "failure"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "regulatory",
    module: "regulatory",
    routes: [{ path: "/regulatory" }],
    titleKey: "regulatory.title",
    summaryKey: "regulatory.summary",
    purposeKey: "regulatory.purpose",
    prerequisiteKeys: ["regulatory.prerequisites.0"],
    quickStartStepKeys: ["regulatory.quickStart.0", "regulatory.quickStart.1"],
    sectionKeys: ["regulatory.sections.0", "regulatory.sections.1", "regulatory.sections.2"],
    warningKeys: [],
    roleNoteKeys: ["regulatory.roleNotes.0"],
    knownLimitationKeys: ["regulatory.limitations.0"],
    relatedTopicIds: ["dossiers", "claimsLabels", "approval"],
    glossaryTermIds: ["jurisdiction", "evidenceConfirmation"],
    screenshotIds: [],
    keywords: ["classification", "rules", "reviews", "kenya", "eac"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "dossiers",
    module: "regulatory",
    routes: [{ path: "/dossiers" }],
    titleKey: "dossiers.title",
    summaryKey: "dossiers.summary",
    purposeKey: "dossiers.purpose",
    prerequisiteKeys: ["dossiers.prerequisites.0"],
    quickStartStepKeys: ["dossiers.quickStart.0", "dossiers.quickStart.1"],
    sectionKeys: [
      "dossiers.sections.0", "dossiers.sections.1", "dossiers.sections.2", "dossiers.sections.3",
      "dossiers.sections.4", "dossiers.sections.5", "dossiers.sections.6", "dossiers.sections.7",
    ],
    warningKeys: [],
    roleNoteKeys: ["dossiers.roleNotes.0"],
    knownLimitationKeys: ["dossiers.limitations.0"],
    relatedTopicIds: ["regulatory", "claimsLabels", "reports"],
    glossaryTermIds: ["dossier", "watermark", "auditEvent"],
    screenshotIds: [],
    tourId: "dossiers",
    keywords: ["dossier", "evidence matrix", "pdf export", "docx export", "submission"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "claimsLabels",
    module: "regulatory",
    routes: [{ path: "/claims-labels" }],
    titleKey: "claimsLabels.title",
    summaryKey: "claimsLabels.summary",
    purposeKey: "claimsLabels.purpose",
    prerequisiteKeys: ["claimsLabels.prerequisites.0"],
    quickStartStepKeys: ["claimsLabels.quickStart.0", "claimsLabels.quickStart.1"],
    sectionKeys: ["claimsLabels.sections.0", "claimsLabels.sections.1", "claimsLabels.sections.2", "claimsLabels.sections.3"],
    warningKeys: [],
    roleNoteKeys: ["claimsLabels.roleNotes.0"],
    knownLimitationKeys: ["claimsLabels.limitations.0"],
    relatedTopicIds: ["dossiers", "regulatory", "approval"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["claim", "label", "artwork", "consistency check"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "approval",
    module: "regulatory",
    routes: [{ path: "/approval" }],
    titleKey: "approval.title",
    summaryKey: "approval.summary",
    purposeKey: "approval.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["approval.quickStart.0", "approval.quickStart.1"],
    sectionKeys: ["approval.sections.0", "approval.sections.1", "approval.sections.2"],
    warningKeys: ["approval.warnings.0"],
    roleNoteKeys: ["approval.roleNotes.0"],
    knownLimitationKeys: [],
    relatedTopicIds: ["formulation", "regulatory", "dossiers", "claimsLabels"],
    glossaryTermIds: ["approvalRole", "readinessBlocker"],
    screenshotIds: [],
    keywords: ["approve", "pilot approved", "production approved", "policy", "blocker"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "reports",
    module: "reports",
    routes: [{ path: "/reports" }],
    titleKey: "reports.title",
    summaryKey: "reports.summary",
    purposeKey: "reports.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["reports.quickStart.0"],
    sectionKeys: [],
    warningKeys: [],
    roleNoteKeys: [],
    knownLimitationKeys: ["reports.limitations.0"],
    relatedTopicIds: ["dossiers", "dataExchange"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["reports", "export", "audit report"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "dataExchange",
    module: "dataExchange",
    routes: [{ path: "/data-exchange" }],
    titleKey: "dataExchange.title",
    summaryKey: "dataExchange.summary",
    purposeKey: "dataExchange.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["dataExchange.quickStart.0", "dataExchange.quickStart.1", "dataExchange.quickStart.2"],
    sectionKeys: [
      "dataExchange.sections.0", "dataExchange.sections.1", "dataExchange.sections.2",
      "dataExchange.sections.3", "dataExchange.sections.4", "dataExchange.sections.5", "dataExchange.sections.6",
    ],
    warningKeys: [],
    roleNoteKeys: ["dataExchange.roleNotes.0"],
    knownLimitationKeys: ["dataExchange.limitations.0"],
    relatedTopicIds: ["administration", "reports"],
    glossaryTermIds: ["dataExchangeTemplate"],
    screenshotIds: [],
    keywords: ["import", "export", "csv", "excel", "template", "preview", "commit"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "administration",
    module: "administration",
    routes: [{ path: "/administration" }],
    titleKey: "administration.title",
    summaryKey: "administration.summary",
    purposeKey: "administration.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["administration.quickStart.0"],
    sectionKeys: [],
    warningKeys: [],
    roleNoteKeys: [],
    knownLimitationKeys: ["administration.limitations.0"],
    relatedTopicIds: ["materials", "regulatory", "approval", "dataExchange", "settings"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["administration", "test definitions", "configuration"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "materials",
    module: "materials",
    routes: [{ path: "/materials" }],
    linkOnly: true,
    titleKey: "materials.title",
    summaryKey: "materials.summary",
    purposeKey: "materials.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["materials.quickStart.0", "materials.quickStart.1"],
    sectionKeys: ["materials.sections.0", "materials.sections.1", "materials.sections.2", "materials.sections.3"],
    warningKeys: [],
    roleNoteKeys: [],
    knownLimitationKeys: [],
    relatedTopicIds: ["administration", "formulation"],
    glossaryTermIds: ["landedCost"],
    screenshotIds: [],
    keywords: ["material", "supplier", "packaging", "factory profile", "inventory"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "notebooks",
    module: "tools",
    routes: [{ path: "/notebooks" }],
    titleKey: "notebooks.title",
    summaryKey: "notebooks.summary",
    purposeKey: "notebooks.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["notebooks.quickStart.0"],
    sectionKeys: [],
    warningKeys: [],
    roleNoteKeys: [],
    knownLimitationKeys: ["notebooks.limitations.0"],
    relatedTopicIds: ["files", "runs"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["notebook", "jupyter", "cell", "run"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "files",
    module: "tools",
    routes: [{ path: "/files" }],
    titleKey: "files.title",
    summaryKey: "files.summary",
    purposeKey: "files.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["files.quickStart.0"],
    sectionKeys: [],
    warningKeys: [],
    roleNoteKeys: [],
    knownLimitationKeys: [],
    relatedTopicIds: ["notebooks", "runs"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["files", "browser", "preview"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "runs",
    module: "tools",
    routes: [{ path: "/runs" }],
    titleKey: "runs.title",
    summaryKey: "runs.summary",
    purposeKey: "runs.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["runs.quickStart.0"],
    sectionKeys: [],
    warningKeys: [],
    roleNoteKeys: [],
    knownLimitationKeys: [],
    relatedTopicIds: ["notebooks", "settings"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["runs", "history", "reproduce", "log"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "sessions",
    module: "sessions",
    routes: [
      { path: "/live", mode: "prefix" },
      { path: "/example/:sessionId" },
    ],
    titleKey: "sessions.title",
    summaryKey: "sessions.summary",
    purposeKey: "sessions.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["sessions.quickStart.0", "sessions.quickStart.1"],
    sectionKeys: [],
    warningKeys: ["sessions.warnings.0"],
    roleNoteKeys: [],
    knownLimitationKeys: [],
    relatedTopicIds: ["home"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["session", "chat", "new session", "history"],
    contentStatus: "current",
  },
  {
    schemaVersion: HELP_SCHEMA_VERSION,
    id: "settings",
    module: "settings",
    routes: [{ path: "/settings", mode: "prefix" }],
    titleKey: "settings.title",
    summaryKey: "settings.summary",
    purposeKey: "settings.purpose",
    prerequisiteKeys: [],
    quickStartStepKeys: ["settings.quickStart.0"],
    sectionKeys: [
      "settings.sections.0", "settings.sections.1", "settings.sections.2",
      "settings.sections.3", "settings.sections.4", "settings.sections.5",
    ],
    warningKeys: [
      "settings.warnings.0",
      "settings.warnings.1",
      "settings.warnings.2",
      "settings.warnings.3",
      "settings.warnings.4",
      "settings.warnings.5",
      "settings.warnings.6",
    ],
    roleNoteKeys: [],
    knownLimitationKeys: [],
    relatedTopicIds: ["administration"],
    glossaryTermIds: [],
    screenshotIds: [],
    keywords: ["settings", "theme", "locale", "model", "compute", "privacy"],
    contentStatus: "current",
  },
];

/** Routes deliberately given no help topic, with why — so "does this
 *  route have coverage" is always an explicit yes/no/excluded, never a
 *  silent gap. Every route in `router.tsx` must be covered by either
 *  `HELP_TOPICS` (directly or via `parentTopicId`/prefix fallback) or an
 *  entry here (checked by the registry test). */
export interface HelpExclusion {
  route: string;
  reason: string;
}

export const HELP_EXCLUSIONS: HelpExclusion[] = [
  { route: "/", reason: "Redirects immediately to /live — never rendered itself." },
  { route: "/formulas", reason: "Redirects to /projects for old bookmarks; never rendered itself." },
  {
    route: "/formulas/legacy",
    reason:
      "The retained pre-Phase-6 single-page Formula Builder, kept only so an old deep link " +
      "never 404s. Deliberately not taught as the primary path (see PHASE10_COVERAGE_MATRIX.md " +
      "\"Legacy\" row, help level: none) — its functionality is documented under the current " +
      "Formulation/Laboratory/Stability/Regulatory/Approval topics instead.",
  },
  { route: "*", reason: "The 404 catch-all — has nothing to explain." },
  {
    route: "/guide",
    reason:
      "The in-app illustrated user guide (Phase 10 Session 6) — its own content already explains the whole app; " +
      "a Help panel about the Help guide would be redundant. Reachable from the Help Center and command palette.",
  },
];

/**
 * Resolve the help topic for a real pathname (e.g. from `useLocation()`).
 * Two passes, most-specific first: an exact/parameterized match against
 * every "exact"-mode route (covers every real route in this app today —
 * `matchPath` itself handles `:param` segments, no hand-rolled parsing),
 * then a `mode: "prefix"` match — the parent-topic fallback a nested path
 * like `/settings/appearance` or `/live/<id>` needs when only its base
 * path (`/settings`, `/live`) is registered. A topic never matches a
 * route it doesn't list; there is no implicit "looks similar" fallback.
 */
export function topicForRoute(pathname: string): HelpTopic | undefined {
  for (const topic of HELP_TOPICS) {
    for (const route of topic.routes) {
      if (route.mode === "prefix") continue; // second pass only
      if (matchPath({ path: route.path, end: true }, pathname)) return topic;
    }
  }
  for (const topic of HELP_TOPICS) {
    for (const route of topic.routes) {
      if (route.mode === "prefix" && matchPath({ path: route.path, end: false }, pathname)) return topic;
    }
  }
  return undefined;
}

export function getTopic(id: string): HelpTopic | undefined {
  return HELP_TOPICS.find((t) => t.id === id);
}

export function relatedTopics(topic: HelpTopic): HelpTopic[] {
  return topic.relatedTopicIds.map(getTopic).filter((t): t is HelpTopic => t !== undefined);
}

export function isExcludedRoute(route: string): boolean {
  return HELP_EXCLUSIONS.some((e) => e.route === route);
}
