import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import {
  TARGET_MARKETS,
  templateForFamily,
  type Formulation,
  type ProductCatalog,
} from "@ai4s/shared";
import { newFormulation } from "@/lib/formulations";
import { cn } from "@/lib/cn";

/**
 * Start a formulation project.
 *
 * The product family is chosen first because it decides everything downstream:
 * which packaging SKUs are available, which structural template applies, and
 * whether the product needs a preservative and an INCI declaration. Choosing a
 * family is a real decision, not a label.
 */
export function NewProjectDialog({
  catalog,
  onCancel,
  onCreate,
}: {
  catalog: ProductCatalog;
  onCancel: () => void;
  onCreate: (project: Formulation) => Promise<unknown>;
}) {
  const { t } = useTranslation(["session", "common"]);
  const [name, setName] = useState("");
  const [code, setCode] = useState("");
  const [familyCode, setFamilyCode] = useState("");
  const [skuCodes, setSkuCodes] = useState<string[]>([]);
  const [market, setMarket] = useState<string>("KE");
  const [brief, setBrief] = useState("");
  const [claims, setClaims] = useState("");
  const [batchKg, setBatchKg] = useState("100");
  const [busy, setBusy] = useState(false);

  const families = useMemo(
    () => [...catalog.families].sort((a, b) => a.name.localeCompare(b.name)),
    [catalog],
  );
  const skus = useMemo(
    () => catalog.skus.filter((s) => s.productFamilyCode === familyCode),
    [catalog, familyCode],
  );
  const template = familyCode ? templateForFamily(familyCode) : undefined;

  const canSubmit = name.trim().length > 0 && familyCode.length > 0 && !busy;

  const submit = async () => {
    if (!canSubmit) return;
    setBusy(true);
    try {
      await onCreate(
        newFormulation(name.trim(), familyCode, {
          code: code.trim() || undefined,
          targetSkuCodes: skuCodes,
          targetMarkets: [market],
          brief: brief.trim() || undefined,
          targetClaims: claims
            .split("\n")
            .map((c) => c.trim())
            .filter(Boolean),
          targetBatchKg: batchKg || "100",
        }),
      );
    } finally {
      setBusy(false);
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/40 p-6"
      role="dialog"
      aria-modal="true"
      aria-label={t("builder.newProject")}
    >
      <div className="my-auto w-[40rem] max-w-full rounded-card border border-border bg-surface shadow-xl">
        <h2 className="border-b border-border px-5 py-3 text-[14px] font-medium text-text">
          {t("builder.newProject")}
        </h2>

        <div className="space-y-3 px-5 py-4">
          <div className="grid gap-3 sm:grid-cols-2">
            <Field label={t("builder.projectName")} required>
              <input
                autoFocus
                value={name}
                onChange={(e) => setName(e.target.value)}
                className={inputClass}
                aria-label={t("builder.projectName")}
              />
            </Field>
            <Field label={t("builder.projectCode")} hint={t("builder.projectCodeHint")}>
              <input
                value={code}
                onChange={(e) => setCode(e.target.value)}
                placeholder={t("builder.autoGenerated")}
                className={inputClass}
                aria-label={t("builder.projectCode")}
              />
            </Field>
          </div>

          <Field label={t("builder.productFamily")} required>
            <select
              value={familyCode}
              onChange={(e) => {
                setFamilyCode(e.target.value);
                setSkuCodes([]);
              }}
              className={inputClass}
              aria-label={t("builder.productFamily")}
            >
              <option value="">{t("builder.selectFamily")}</option>
              {families.map((f) => (
                <option key={f.code} value={f.code}>
                  {f.name} ({f.code})
                </option>
              ))}
            </select>
          </Field>

          {template && (
            <div className="rounded-input border border-border bg-surface-2 px-3 py-2 text-[11px] text-muted">
              <div className="mb-1 font-medium text-text">{template.name}</div>
              <div>
                {t("builder.templateRoles")}:{" "}
                {template.requiredFunctions.map((f) => f.replace(/_/g, " ")).join(", ")}
              </div>
              <div className="mt-1">{t("builder.templateDisclaimer")}</div>
            </div>
          )}

          {skus.length > 0 && (
            <Field label={t("builder.targetSkus")} hint={t("builder.targetSkusHint")}>
              <div className="max-h-32 space-y-0.5 overflow-y-auto rounded-input border border-border p-2">
                {skus.map((s) => (
                  <label key={s.skuCode} className="flex items-center gap-2 text-[12px] text-text">
                    <input
                      type="checkbox"
                      checked={skuCodes.includes(s.skuCode)}
                      onChange={() =>
                        setSkuCodes((prev) =>
                          prev.includes(s.skuCode)
                            ? prev.filter((c) => c !== s.skuCode)
                            : [...prev, s.skuCode],
                        )
                      }
                    />
                    {s.displayName}
                  </label>
                ))}
              </div>
            </Field>
          )}

          <div className="grid gap-3 sm:grid-cols-2">
            <Field label={t("builder.marketLabel")}>
              <select
                value={market}
                onChange={(e) => setMarket(e.target.value)}
                className={inputClass}
                aria-label={t("builder.marketLabel")}
              >
                {TARGET_MARKETS.map((m) => (
                  <option key={m} value={m}>
                    {t(`builder.market.${m}`)}
                  </option>
                ))}
              </select>
            </Field>
            <Field label={t("builder.targetBatch")}>
              <input
                value={batchKg}
                onChange={(e) => setBatchKg(e.target.value)}
                inputMode="decimal"
                className={inputClass}
                aria-label={t("builder.targetBatch")}
              />
            </Field>
          </div>

          <Field label={t("builder.brief")}>
            <textarea
              value={brief}
              onChange={(e) => setBrief(e.target.value)}
              rows={3}
              className={cn(inputClass, "resize-y")}
              aria-label={t("builder.brief")}
            />
          </Field>

          <Field label={t("builder.claims")} hint={t("builder.claimsHint")}>
            <textarea
              value={claims}
              onChange={(e) => setClaims(e.target.value)}
              rows={2}
              className={cn(inputClass, "resize-y")}
              aria-label={t("builder.claims")}
            />
          </Field>
        </div>

        <div className="flex justify-end gap-2 border-t border-border px-5 py-3">
          <button
            onClick={onCancel}
            className="rounded-input border border-border px-3 py-1.5 text-xs text-muted hover:bg-surface-2 hover:text-text"
          >
            {t("common:actions.cancel")}
          </button>
          <button
            onClick={submit}
            disabled={!canSubmit}
            className="rounded-input bg-accent px-3 py-1.5 text-xs font-medium text-accent-fg hover:opacity-90 disabled:opacity-40"
          >
            {t("builder.create")}
          </button>
        </div>
      </div>
    </div>
  );
}

const inputClass =
  "w-full rounded-input border border-border bg-surface px-2 py-1.5 text-[12px] text-text outline-none focus:border-accent";

function Field({
  label,
  hint,
  required,
  children,
}: {
  label: string;
  hint?: string;
  required?: boolean;
  children: React.ReactNode;
}) {
  return (
    <label className="block">
      <span className="mb-1 block text-[11px] font-medium text-muted">
        {label}
        {required && <span className="text-error"> *</span>}
      </span>
      {children}
      {hint && <span className="mt-0.5 block text-[10px] text-muted">{hint}</span>}
    </label>
  );
}
