/**
 * Phase 8 — one deterministic intermediate content model built from a
 * `DossierExportSnapshot` (`@ai4s/shared`, Session 2), consumed by BOTH
 * `dossierPdf.ts` and `dossierDocx.ts` so the two renderers can never
 * silently diverge on what they include. Building this array is a pure
 * map over already-deterministic snapshot data — no `Date.now()`, no
 * randomness, no DOM/HTML involved.
 */
import type { DossierExportSnapshot } from "@ai4s/shared";
import { computeSnapshotWatermark } from "./watermark";

export type DocumentContentBlock =
  | { kind: "title"; text: string }
  | { kind: "heading"; text: string }
  | { kind: "paragraph"; text: string }
  | { kind: "keyValue"; label: string; value: string }
  | { kind: "warning"; text: string }
  | { kind: "listItem"; text: string };

export interface RenderOptions {
  /** Overrides the default `Regulatory Dossier — <code>` title. */
  title?: string;
  locale?: string;
}

const BLANK = "unknown";

/** Never coerces a missing value to `0`/`""` — an absent field reads as
 *  the literal word "unknown", exactly like the rest of this app's
 *  blank-value convention. */
function blankOr(value: string | number | undefined | null): string {
  if (value === undefined || value === null) return BLANK;
  const str = String(value);
  return str.trim().length > 0 ? str : BLANK;
}

export function buildDossierDocumentContent(snapshot: DossierExportSnapshot, options: RenderOptions = {}): DocumentContentBlock[] {
  const blocks: DocumentContentBlock[] = [];
  const watermark = computeSnapshotWatermark(snapshot.source.approvalStatusAtGeneration);
  const title = options.title ?? `Regulatory Dossier — ${snapshot.dossierCode}`;

  blocks.push({ kind: "title", text: title });
  if (watermark.text) blocks.push({ kind: "warning", text: watermark.text });

  blocks.push({ kind: "heading", text: "Document Identity" });
  blocks.push({ kind: "keyValue", label: "Dossier code", value: blankOr(snapshot.dossierCode) });
  blocks.push({ kind: "keyValue", label: "Dossier title", value: blankOr(snapshot.dossierTitle) });
  blocks.push({ kind: "keyValue", label: "Revision", value: blankOr(snapshot.meta.dossierRevision) });
  blocks.push({ kind: "keyValue", label: "Dossier status", value: blankOr(snapshot.dossierStatus) });
  blocks.push({ kind: "keyValue", label: "Jurisdiction(s)", value: snapshot.meta.jurisdictions.length > 0 ? snapshot.meta.jurisdictions.join(", ") : BLANK });
  blocks.push({ kind: "keyValue", label: "Packaging SKU", value: blankOr(snapshot.meta.packagingSkuCode) });
  blocks.push({ kind: "keyValue", label: "Source formula version", value: blankOr(snapshot.source.formulaVersionId) });
  blocks.push({ kind: "keyValue", label: "Approval status at generation", value: blankOr(snapshot.source.approvalStatusAtGeneration) });
  blocks.push({ kind: "keyValue", label: "Generated at", value: blankOr(snapshot.generationTimestamp) });
  blocks.push({ kind: "keyValue", label: "Generated by", value: blankOr(snapshot.generatedBy) });

  blocks.push({ kind: "heading", text: "Readiness Summary" });
  blocks.push({ kind: "keyValue", label: "Overall readiness", value: blankOr(snapshot.readiness.overallReadiness) });
  blocks.push({ kind: "keyValue", label: "Mandatory requirements satisfied", value: `${snapshot.readiness.satisfiedMandatoryRequirements} / ${snapshot.readiness.mandatoryRequirements}` });
  blocks.push({ kind: "keyValue", label: "Missing mandatory requirements", value: blankOr(snapshot.readiness.missingMandatoryRequirements) });
  blocks.push({ kind: "keyValue", label: "Expired evidence items", value: blankOr(snapshot.readiness.expiredEvidenceCount) });
  blocks.push({ kind: "keyValue", label: "Rejected evidence items", value: blankOr(snapshot.readiness.rejectedEvidenceCount) });
  blocks.push({ kind: "keyValue", label: "Human review required", value: blankOr(snapshot.readiness.humanReviewRequiredCount) });

  blocks.push({ kind: "heading", text: "Requirements" });
  if (snapshot.requirements.length === 0) {
    blocks.push({ kind: "paragraph", text: "No requirements recorded for this revision." });
  }
  for (const r of snapshot.requirements) {
    const flags = [r.mandatory ? "mandatory" : "optional", r.critical ? "critical" : undefined].filter(Boolean).join(", ");
    blocks.push({ kind: "listItem", text: `${r.requirementCode} — ${r.title} [${r.applicabilityStatus}; ${flags}]` });
  }

  blocks.push({ kind: "heading", text: "Evidence Matrix" });
  if (snapshot.evidenceMatrix.length === 0) {
    blocks.push({ kind: "paragraph", text: "No requirement rows to evaluate." });
  }
  for (const row of snapshot.evidenceMatrix) {
    const blockingSuffix = row.blockingReason ? ` (blocking: ${row.blockingReason})` : "";
    blocks.push({ kind: "listItem", text: `${row.requirement.requirementCode}: ${row.satisfaction}${blockingSuffix}` });
  }

  blocks.push({ kind: "heading", text: "Evidence Items" });
  if (snapshot.evidenceItems.length === 0) {
    blocks.push({ kind: "paragraph", text: "No evidence items referenced by an included requirement link." });
  }
  for (const e of snapshot.evidenceItems) {
    const supersedes = e.supersedesEvidenceId ? ` — supersedes ${e.supersedesEvidenceId}` : "";
    blocks.push({ kind: "listItem", text: `${e.title} — ${e.evidenceType}, status: ${e.status}${supersedes}` });
  }

  blocks.push({ kind: "heading", text: "Reviews" });
  if (snapshot.reviews.length === 0) {
    blocks.push({ kind: "paragraph", text: "No reviews recorded for this revision." });
  }
  for (const r of snapshot.reviews) {
    blocks.push({ kind: "listItem", text: `${r.reviewedAt} — ${r.reviewedBy} (${r.reviewerRole}): ${r.outcome}` });
  }
  if (snapshot.reviewRevocations.length > 0) {
    blocks.push({ kind: "paragraph", text: "Review revocations:" });
    for (const rv of snapshot.reviewRevocations) {
      blocks.push({ kind: "listItem", text: `Revokes ${rv.revokesReviewId} — ${rv.revokedBy}: ${rv.reason}` });
    }
  }

  blocks.push({ kind: "heading", text: "Submissions" });
  blocks.push({ kind: "paragraph", text: "Internal submission tracking only — not confirmation of regulatory authority approval." });
  if (snapshot.submissions.length === 0) {
    blocks.push({ kind: "paragraph", text: "No submissions recorded for this revision." });
  }
  for (const s of snapshot.submissions) {
    blocks.push({ kind: "listItem", text: `${s.submittedAt} — ${s.jurisdiction}: ${s.status}` });
  }

  blocks.push({ kind: "heading", text: "Warnings" });
  if (snapshot.warnings.length === 0) {
    blocks.push({ kind: "paragraph", text: "None." });
  }
  for (const w of snapshot.warnings) blocks.push({ kind: "listItem", text: w });

  blocks.push({ kind: "heading", text: "Assumptions and Limitations" });
  for (const a of snapshot.assumptions) blocks.push({ kind: "listItem", text: a });

  return blocks;
}
