/**
 * Phase 8 — deterministic DOCX rendering of a `DossierExportSnapshot`.
 * Built from the same `buildDossierDocumentContent` intermediate model
 * `dossierPdf.ts` uses — never a second, independently-maintained view
 * of what a dossier export contains.
 *
 * Known non-determinism: the `docx` package's public API exposes no way
 * to override its zip-archive/core-properties timestamps (verified
 * against its own type definitions), so byte-for-byte output is not
 * guaranteed even for identical input — see the render engine test file
 * for the structural-equality comparison this uses instead.
 */
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import type { DossierExportSnapshot } from "@formulab/shared";
import { buildDossierDocumentContent, type RenderOptions } from "./content";

export async function renderDossierDocx(snapshot: DossierExportSnapshot, options: RenderOptions = {}): Promise<Uint8Array> {
  const content = buildDossierDocumentContent(snapshot, options);
  const title = options.title ?? `Regulatory Dossier — ${snapshot.dossierCode}`;

  const children: Paragraph[] = content.map((block) => {
    switch (block.kind) {
      case "title":
        return new Paragraph({ text: block.text, heading: HeadingLevel.TITLE });
      case "heading":
        return new Paragraph({ text: block.text, heading: HeadingLevel.HEADING_1 });
      case "warning":
        return new Paragraph({ children: [new TextRun({ text: block.text, bold: true, color: "990000" })] });
      case "keyValue":
        return new Paragraph({
          children: [new TextRun({ text: `${block.label}: `, bold: true }), new TextRun({ text: block.value })],
        });
      case "listItem":
        return new Paragraph({ text: block.text, bullet: { level: 0 } });
      case "paragraph":
        return new Paragraph({ text: block.text });
    }
  });

  const doc = new Document({
    creator: snapshot.generatedBy,
    title,
    subject: `Dossier ${snapshot.dossierCode} revision ${snapshot.meta.dossierRevision}`,
    description: "Generated by FormuLab — decision support only, never a regulatory submission or approval.",
    lastModifiedBy: snapshot.generatedBy,
    sections: [{ children }],
  });

  const arrayBuffer = await Packer.toArrayBuffer(doc);
  return new Uint8Array(arrayBuffer);
}
