/**
 * Seed safety rules.
 *
 * Same caveat as the compatibility seed set: general formulation/handling
 * knowledge, not a transcription of a specific regulation or SDS, and NOT
 * exhaustive. `sourceReferences` stays empty rather than invented; anything
 * whose exact wording or threshold should be checked by a chemist before
 * being relied on is marked `human_review_required`, not "verified".
 *
 * "Medical or therapeutic claim escalation" (the seventeenth category named
 * in the platform's safety-engine specification) is deliberately not a
 * per-line rule here — a claim is a property of the project, not a formula
 * line, so it is handled by `classifyProductSafety` in `engine/safety.ts`
 * instead, which reads the project's target claims directly.
 */
import type { SafetyRule } from "../schemas/safety";

const now = "2026-01-01T00:00:00.000Z";

function rule(
  r: Omit<SafetyRule, "schemaVersion" | "version" | "status" | "active" | "createdAt" | "updatedAt" | "alwaysRequiresHumanReview"> &
    Partial<Pick<SafetyRule, "alwaysRequiresHumanReview">>,
): SafetyRule {
  return {
    schemaVersion: "1.0",
    version: "1.0",
    status: "draft",
    active: true,
    createdAt: now,
    updatedAt: now,
    alwaysRequiresHumanReview: false,
    ...r,
  };
}

export const SEED_SAFETY_RULES: SafetyRule[] = [
  rule({
    id: "safety-acid-hypochlorite",
    name: "Acid plus hypochlorite",
    category: "acid_hypochlorite",
    severity: "blocking",
    ruleType: "forbidden_combination",
    conditions: [
      { label: "hypochlorite", nameKeywordsAny: ["hypochlorite", "bleach", "javel"], functionsAny: ["bleaching_agent"] },
      { label: "acid", nameKeywordsAny: ["hydrochloric", "sulfamic", "citric acid", "acetic acid", "strong acid"], functionsAny: ["ph_adjuster"] },
    ],
    message: "Hypochlorite and an acid are both present. This releases chlorine gas and is a physical hazard to anyone handling or mixing the formula.",
    scientificReason: "Acid protonates hypochlorite to hypochlorous acid, which decomposes to chlorine gas.",
    requiredAction: "Remove one of the two lines. This combination must not be produced or dosed together under any circumstances.",
    requiredPpe: ["chemical splash goggles", "chemical-resistant gloves", "respiratory protection if mixed accidentally"],
    requiredEngineeringControls: ["local exhaust ventilation", "segregated storage from acids"],
    sourceReferences: [],
    verificationStatus: "human_review_required",
    alwaysRequiresHumanReview: true,
  }),
  rule({
    id: "safety-hypochlorite-amine",
    name: "Hypochlorite plus ammonia or amines",
    category: "hypochlorite_amine",
    severity: "blocking",
    ruleType: "forbidden_combination",
    conditions: [
      { label: "hypochlorite", nameKeywordsAny: ["hypochlorite", "bleach", "javel"], functionsAny: ["bleaching_agent"] },
      { label: "amine", nameKeywordsAny: ["ammonia", "amine", "amino"], functionsAny: ["cationic_surfactant"] },
    ],
    message: "Hypochlorite and an ammonia/amine-bearing material are both present. This releases toxic chloramine gases.",
    scientificReason: "Hypochlorite reacts with amine nitrogen to form mono-, di- and trichloramine.",
    requiredAction: "Remove one of the two lines. This combination must not be produced or dosed together under any circumstances.",
    requiredPpe: ["respiratory protection", "chemical splash goggles", "chemical-resistant gloves"],
    requiredEngineeringControls: ["local exhaust ventilation", "segregated storage from ammonia/amine products"],
    sourceReferences: [],
    verificationStatus: "human_review_required",
    alwaysRequiresHumanReview: true,
  }),
  rule({
    id: "safety-oxidizer-reducer",
    name: "Strong oxidizer plus reducer",
    category: "oxidizer_reducer",
    severity: "error",
    ruleType: "forbidden_combination",
    conditions: [
      { label: "oxidizer", functionsAny: ["bleaching_agent", "oxygen_donor"] },
      { label: "reducer", functionsAny: ["antioxidant"] },
    ],
    message: "A strong oxidiser and a reducing agent are both present. Beyond the compatibility loss, concentrated oxidiser/reducer mixes can be an exothermic hazard depending on concentration and confinement.",
    scientificReason: "Redox reaction between the two; heat release scales with concentration and how well the container vents.",
    requiredAction: "Confirm reaction heat and gas evolution at bench scale in an open, ventilated vessel before any batch scale-up.",
    requiredPpe: ["chemical splash goggles", "chemical-resistant gloves"],
    requiredEngineeringControls: ["local exhaust ventilation"],
    sourceReferences: [],
    verificationStatus: "not_verified",
  }),
  rule({
    id: "safety-corrosivity",
    name: "High corrosivity risk",
    category: "corrosivity",
    severity: "error",
    ruleType: "ph_dependent",
    conditions: [{ label: "ph-relevant", functionsAny: ["ph_adjuster", "builder", "bleaching_agent"], phMin: "2", phMax: "12.5" }],
    message: "The formula's target pH is outside 2–12.5. Formulas this acidic or alkaline are typically classified skin/eye corrosive.",
    scientificReason: "GHS skin-corrosion criteria commonly use pH ≤2 or ≥11.5–12.5 as a screening trigger, refined by exposure-time data.",
    requiredAction: "Confirm the GHS corrosivity classification and required label statements before production.",
    requiredPpe: ["chemical splash goggles", "chemical-resistant gloves", "apron"],
    requiredEngineeringControls: [],
    sourceReferences: [],
    verificationStatus: "human_review_required",
    alwaysRequiresHumanReview: true,
  }),
  rule({
    id: "safety-ph-irritation",
    name: "High or low pH risk",
    category: "ph_extreme",
    severity: "warning",
    ruleType: "ph_dependent",
    conditions: [
      {
        label: "formula",
        functionsAny: ["anionic_surfactant", "nonionic_surfactant", "amphoteric_surfactant", "cationic_surfactant", "builder", "ph_adjuster", "disinfectant_active"],
        phMin: "4",
        phMax: "10",
      },
    ],
    message: "The formula's target pH is outside a mild 4–10 band. This does not necessarily mean the product is corrosive, but irritation risk should be checked.",
    scientificReason: "Products near skin-neutral pH (~5.5) are generally best tolerated; the further outside 4–10, the more likely irritation testing is warranted.",
    requiredAction: "Consider a human-repeat-insult-patch or equivalent irritation assessment if this product contacts skin directly.",
    requiredPpe: [],
    requiredEngineeringControls: [],
    sourceReferences: [],
    verificationStatus: "not_verified",
  }),
  rule({
    id: "safety-flammable-solvent",
    name: "Flammable solvent threshold",
    category: "flammable_solvent_threshold",
    severity: "warning",
    ruleType: "concentration_dependent",
    // maxConcentrationPercent is the ceiling below which this is NOT flagged —
    // the finding fires once the line's percent exceeds it, i.e. at/above 70%.
    conditions: [{ label: "alcohol solvent", functionsAny: ["solvent"], nameKeywordsAny: ["alcohol", "ethanol", "isopropyl", "ipa"], maxConcentrationPercent: "70" }],
    message: "An alcohol-type solvent is present at or above 70%. Formulas at this concentration are commonly flammable-liquid classified.",
    scientificReason: "Ethanol/isopropanol solutions above roughly 60–70% typically have a flash point low enough to classify as a flammable liquid.",
    requiredAction: "Confirm flash point and flammable-liquid classification/labelling before production and storage.",
    requiredPpe: [],
    requiredEngineeringControls: ["no open flame or ignition source nearby", "flammables storage cabinet"],
    sourceReferences: [],
    verificationStatus: "human_review_required",
  }),
  rule({
    id: "safety-restricted-active-threshold",
    name: "Restricted active threshold",
    category: "restricted_active_threshold",
    severity: "warning",
    ruleType: "concentration_dependent",
    conditions: [{ label: "regulated active", functionsAny: ["qac_active", "chlorhexidine_active", "disinfectant_active"], maxConcentrationPercent: "10" }],
    message: "A regulated antimicrobial active is present above 10%. Concentrations this high are unusual for a finished consumer/institutional product and are worth a second look.",
    scientificReason: "Most QAC/chlorhexidine/biocide finished-product use levels are well under 10%; a higher figure is either a concentrate (needing dilution instructions) or a data error.",
    requiredAction: "Confirm this is the intended finished-product concentration, not a raw-material assay figure entered by mistake.",
    requiredPpe: [],
    requiredEngineeringControls: [],
    sourceReferences: [],
    verificationStatus: "not_verified",
    alwaysRequiresHumanReview: true,
  }),
  rule({
    id: "safety-sensitizer-threshold",
    name: "Sensitizer threshold",
    category: "sensitizer_threshold",
    severity: "warning",
    ruleType: "concentration_dependent",
    conditions: [{ label: "fragrance", functionsAny: ["fragrance"], maxConcentrationPercent: "0.5" }],
    message: "Fragrance is present above 0.5%. Several common fragrance allergens have specific labelling thresholds that can be reached at this level.",
    scientificReason: "IFRA and several regional cosmetic regulations set allergen-declaration thresholds around this order of magnitude, allergen-specific.",
    requiredAction: "Confirm the fragrance supplier's allergen declaration and check it against target-market labelling thresholds.",
    requiredPpe: [],
    requiredEngineeringControls: [],
    sourceReferences: [],
    verificationStatus: "not_verified",
  }),
  rule({
    id: "safety-eye-damage",
    name: "Eye-damage risk",
    category: "eye_damage",
    severity: "error",
    ruleType: "forbidden_combination",
    conditions: [{ label: "caustic", nameKeywordsAny: ["sodium hydroxide", "potassium hydroxide", "caustic"], functionsAny: ["ph_adjuster"] }],
    message: "A caustic alkali is present. Concentrated caustic materials are a serious-eye-damage hazard on splash contact.",
    scientificReason: "Strong alkalis cause liquefactive necrosis of ocular tissue on contact; damage can continue after exposure.",
    requiredAction: "Confirm eye-wash station availability wherever this is handled at concentrate strength.",
    requiredPpe: ["chemical splash goggles (not safety glasses alone)"],
    requiredEngineeringControls: ["eye-wash station within reach"],
    sourceReferences: [],
    verificationStatus: "human_review_required",
  }),
  rule({
    id: "safety-skin-corrosion",
    name: "Skin-corrosion risk",
    category: "skin_corrosion",
    severity: "error",
    ruleType: "forbidden_combination",
    conditions: [{ label: "corrosive", nameKeywordsAny: ["hydrochloric", "sulfuric", "sodium hydroxide", "caustic", "concentrated acid"], functionsAny: ["ph_adjuster"] }],
    message: "A material commonly associated with skin-corrosive concentrates is present.",
    scientificReason: "Strong acids/alkalis cause chemical burns on skin contact at concentrate strength.",
    requiredAction: "Confirm concentration and corrosivity classification against the raw material's own SDS before production.",
    requiredPpe: ["chemical-resistant gloves", "apron", "chemical splash goggles"],
    requiredEngineeringControls: [],
    sourceReferences: [],
    verificationStatus: "human_review_required",
  }),
  rule({
    id: "safety-acute-toxicity",
    name: "Acute-toxicity warning",
    category: "acute_toxicity",
    severity: "warning",
    ruleType: "forbidden_combination",
    conditions: [{ label: "acutely toxic candidate", nameKeywordsAny: ["hypochlorite", "formaldehyde", "methanol"], functionsAny: ["bleaching_agent", "disinfectant_active"] }],
    message: "A material commonly carrying an acute-toxicity classification is present.",
    scientificReason: "Several disinfectant/bleaching actives carry acute oral/dermal/inhalation toxicity classifications at use or concentrate strength.",
    requiredAction: "Confirm the material's acute-toxicity classification and category against its SDS before finalising the formula.",
    requiredPpe: [],
    requiredEngineeringControls: [],
    sourceReferences: [],
    verificationStatus: "not_verified",
  }),
  rule({
    id: "safety-environmental-hazard",
    name: "Environmental hazard",
    category: "environmental_hazard",
    severity: "warning",
    ruleType: "forbidden_combination",
    conditions: [{ label: "aquatic-hazard candidate", functionsAny: ["qac_active", "chlorhexidine_active"] }],
    message: "A material with commonly limited biodegradability under aquatic-toxicity assessment is present (QAC/chlorhexidine actives).",
    scientificReason: "Several QAC and biguanide actives are classified hazardous to aquatic life at environmentally relevant concentrations.",
    requiredAction: "Confirm the specific active's aquatic-toxicity and biodegradability data before any environmental claim is made.",
    requiredPpe: [],
    requiredEngineeringControls: ["do not discharge concentrate to drains/waterways"],
    sourceReferences: [],
    verificationStatus: "not_verified",
  }),
  rule({
    id: "safety-dangerous-temperature",
    name: "Dangerous process temperature",
    category: "dangerous_temperature",
    severity: "warning",
    ruleType: "temperature_dependent",
    conditions: [{ label: "heat-sensitive oxidiser", functionsAny: ["bleaching_agent", "oxygen_donor"], maxTemperatureC: "40" }],
    message: "An oxidising active is present and the process temperature is at or above 40°C. Heating an oxidiser can accelerate decomposition, releasing gas and heat faster than a vented vessel may handle.",
    scientificReason: "Decomposition rate of common oxidisers (hypochlorite, percarbonate) roughly doubles for every 10°C rise.",
    requiredAction: "Keep this addition below 40°C and confirm the vessel is adequately vented for any gas release.",
    requiredPpe: [],
    requiredEngineeringControls: ["vessel venting sized for gas evolution", "temperature monitoring"],
    sourceReferences: [],
    verificationStatus: "not_verified",
  }),
  rule({
    id: "safety-unsafe-packaging",
    name: "Unsafe packaging",
    category: "unsafe_packaging",
    severity: "error",
    ruleType: "packaging_incompatibility",
    conditions: [
      { label: "hypochlorite", nameKeywordsAny: ["hypochlorite", "bleach", "javel"], functionsAny: ["bleaching_agent"] },
      { label: "unvented flexible pack", packagingComponentTypesAny: ["pouch", "sachet_film"] },
    ],
    message: "A hypochlorite formula is targeted at a sealed flexible pack. Ongoing gas evolution in an unvented flexible pack risks pack failure over shelf life.",
    scientificReason: "Hypochlorite slowly releases oxygen/chlorine species over storage; a sealed flexible pack has no pressure relief.",
    requiredAction: "Use a vented or rigid, hypochlorite-rated container, or confirm the film/pack is specifically rated for this with the supplier.",
    requiredPpe: [],
    requiredEngineeringControls: [],
    sourceReferences: [],
    verificationStatus: "not_verified",
  }),
  rule({
    id: "safety-required-ppe-reminder",
    name: "Missing required PPE",
    category: "missing_ppe",
    severity: "info",
    ruleType: "forbidden_combination",
    conditions: [{ label: "hazardous handling", functionsAny: ["bleaching_agent", "ph_adjuster", "qac_active", "chlorhexidine_active"] }],
    message: "This formula includes a material class that typically requires PPE beyond routine handling. Listed here so it reaches the batch record, not only the material's own SDS.",
    scientificReason: "Bleaching agents, pH adjusters at concentrate strength and antimicrobial actives commonly carry a PPE requirement on their own SDS.",
    requiredAction: "Confirm PPE requirements against each raw material's SDS before the first production batch.",
    requiredPpe: ["chemical-resistant gloves", "chemical splash goggles"],
    requiredEngineeringControls: [],
    sourceReferences: [],
    verificationStatus: "not_verified",
  }),
  rule({
    id: "safety-ventilation-reminder",
    name: "Missing ventilation requirement",
    category: "missing_ventilation",
    severity: "info",
    ruleType: "forbidden_combination",
    conditions: [{ label: "vapour/gas-generating", functionsAny: ["bleaching_agent", "solvent"] }],
    message: "This formula includes a material class that commonly requires local ventilation during production, beyond routine handling.",
    scientificReason: "Bleaching agents and solvents can generate vapours/gases during mixing that benefit from local exhaust.",
    requiredAction: "Confirm ventilation adequacy at the production site before scale-up.",
    requiredPpe: [],
    requiredEngineeringControls: ["local exhaust ventilation"],
    sourceReferences: [],
    verificationStatus: "not_verified",
  }),
];
